name: Release to prod
on:
  push:
    branches:
      - master-cere
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-cloudfront.yaml@master
    with:
      build_container: 'node:16-buster'
      install_packages_command: 'cp .env.prod .env; sh ./scripts/copy-prod-config.sh; yarn install'
      build_command: 'yarn build'
      path_to_static_files_to_upload: 'build'
      aws_account_id: ${{ vars.PRD_NETWORK_AWS_ACCOUNT_ID }}
      s3_bucket_name: 'bridge.cere.network'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
